//@version=6
indicator(shorttitle="BB + EMA", title="Bollinger Bands with EMA", overlay=true, timeframe="", timeframe_gaps=true)

// --- Inputs ---
// Bollinger Bands Inputs
GRP_BB = "Bollinger Bands"
TT_LENGTH  = "The time period to be used in calculating the MA which creates the base for the Upper and Lower Bands."
TT_MA_TYPE = "Determines the type of Moving Average that is applied to the basis plot line."
TT_SOURCE  = "Determines what data from each bar will be used in calculations."
TT_MULT    = "The number of Standard Deviations away from the MA that the Upper and Lower Bands should be."
TT_OFFSET  = "Changing this number will move the Bollinger Bands either Forwards or Backwards relative to the current market."

bb_len = input.int(20, "Length", minval = 1, tooltip = TT_LENGTH, group = GRP_BB)
bb_maType = input.string("EMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"], tooltip = TT_MA_TYPE, group = GRP_BB)
bb_src = input(close, "Source", tooltip = TT_SOURCE, group = GRP_BB)
bb_mult = input.float(2.0, "StdDev", minval = 0.001, maxval = 50, tooltip = TT_MULT, group = GRP_BB)
bb_offset = input.int(0, "Offset", minval = -500, maxval = 500, tooltip = TT_OFFSET, group = GRP_BB)

// Standalone EMA Inputs
GRP_EMA = "Standalone EMA"
ema_len = input.int(50, "Length", minval=1, group = GRP_EMA)
ema_src = input(close, "Source", group = GRP_EMA)
ema_offset = input.int(0, "Offset", minval=-500, maxval=500, group = GRP_EMA)

// --- Calculations ---
// Generic MA Calculation Function
ma(source, length, _type) =>
    switch _type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA (RMA)" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)

// Bollinger Bands Calculation
basis = ma(bb_src, bb_len, bb_maType)
dev = bb_mult * ta.stdev(bb_src, bb_len)
upper = basis + dev
lower = basis - dev

// Standalone EMA Calculation
ema150 = ta.ema(ema_src, ema_len)

// --- Color Logic ---
line_color = basis > ema150 ? color.green : color.red

// --- Plots ---
plot(basis, "Basis", color=line_color, offset = bb_offset, linewidth=1)
p1 = plot(upper, "Upper", color=color.new(#F23645, 0), offset = bb_offset)
p2 = plot(lower, "Lower", color=color.new(#089981, 0), offset = bb_offset)
fill(p1, p2, title = "Background", color=color.new(line_color, 90))

plot(ema150, title="150 EMA", color=line_color, offset=ema_offset, linewidth=2)
